version: '3.9'
services:

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    networks:
      - techfix-network

  request-service:
    build: ./request-service
    container_name: request-service
    ports:
      - "8081:8081"
    networks:
      - techfix-network
    depends_on:
      - auth-service

  gateway-server:
    build: ./gateway-server
    container_name: gateway-server
    ports:
      - "8085:8085"
    networks:
      - techfix-network
    depends_on:
      - auth-service
      - request-service

networks:
  techfix-network:
    driver: bridge
